# 第6章 NumPy向量计算

除了提供很多好用的官方库之外，Python社区也贡献了很多解决特定问题的第三方库。用于Python的量化解决方案NumPy，就是其中的佼佼者。在本章中，我们将主要讨论NumPy数组的构建、方法和属性、NumPy的广播和布尔索引等。

本章学习要点

[ ] 掌握NumPy数组的使用

[ ] 理解爱因斯坦求和约定

[ ] 理解NumPy约减的轴方向

[ ] 理解NumPy的布尔索引

[ ] 掌握NumPy的广播技术

[ ] 掌握NumPy中随机模块的使用方法

## 6.1 为何需要NumPy

## 6.2 如何导入NumPy

In [2]:
import numpy as np

## 6.3 生成NumPy数组

NumPy最重要的一个特点就是支持N维数组对象ndarray。NumPy的数组只能是同一种数据类型。

### 6.3.1 利用序列生成

In [3]:
data1 = [7,8,5,5,1]
arr1 = np.array(data1)
arr1
type(arr1)

numpy.ndarray

In [4]:
# 查看数组的数据等类型
arr1.dtype

dtype('int64')

In [5]:
# 指定数据类型
arr1 = arr1.astype('float64')
arr1.dtype

dtype('float64')

### 6.3.2 利用特定函数生成

比如```np.arange```可以直接生成，函数的原型如下：

```
arange(start,stop,step,dtype)

```

In [7]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr3 = arr3+1
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

重要的“广播”机制，arr3是一个包含10个元素的向量[0,1,2,3,4,5,6,7,8,9]，它和标量1实施相加的时候，是利用了‘广播’机制，将标量扩展为[1,1,1,1,1,1,1,1,1,1]，然后进行相加

同时，arange是可以将步长设置为浮点数

In [9]:
np.arange(0,10,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

上面的的代码就代表，从0开始，到10结束，每间隔0.5生成一个数字

同时，希望在指定区间内生成指定个数的数组，且要求数组内元素之间的间隔相等，是不需要自己计算步长，可以直接使用```np.linspace(1，10，20)```，代表从1开始，到10结束，生成20个元素，中间间隔相等

In [10]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 6.3.3 Numpy数组的其他常用函数

除了上面介绍的```np.arange()```、```np.linspace()```之外，还有```np.zeros()```、```np.ones()```函数，生成指定维度和填充固定数值的数组。

```np.zeros()```，生成的数组全都用零来填充

```np.ones()```，生成的数组全都用一来填充

通常是用来初始化

In [ ]:
zeros = np.zeros((3,4)) # 生成尺寸为 3 * 4的二维数组
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

特别需要注意 上面的代码中，(3,4)是可以视为匿名元组，也是等价为 ```np.zeros(shape=(3,4))```

但确实两组括号不利于代码阅读，一般会推荐写为 ```np.zeros(shape = [3,4]) ```