# 第6章 NumPy向量计算

除了提供很多好用的官方库之外，Python社区也贡献了很多解决特定问题的第三方库。用于Python的量化解决方案NumPy，就是其中的佼佼者。在本章中，我们将主要讨论NumPy数组的构建、方法和属性、NumPy的广播和布尔索引等。

本章学习要点

[ ] 掌握NumPy数组的使用

[ ] 理解爱因斯坦求和约定

[ ] 理解NumPy约减的轴方向

[ ] 理解NumPy的布尔索引

[ ] 掌握NumPy的广播技术

[ ] 掌握NumPy中随机模块的使用方法

## 6.1 为何需要NumPy

## 6.2 如何导入NumPy

In [1]:
import numpy as np

## 6.3 生成NumPy数组

NumPy最重要的一个特点就是支持N维数组对象ndarray。NumPy的数组只能是同一种数据类型。

### 6.3.1 利用序列生成

In [3]:
data1 = [7,8,5,5,1]
arr1 = np.array(data1)
arr1
type(arr1)

numpy.ndarray

In [4]:
# 查看数组的数据等类型
arr1.dtype

dtype('int64')

In [5]:
# 指定数据类型
arr1 = arr1.astype('float64')
arr1.dtype

dtype('float64')

### 6.3.2 利用特定函数生成

比如```np.arange```可以直接生成，函数的原型如下：

```
arange(start,stop,step,dtype)

```

In [7]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr3 = arr3+1
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

重要的“广播”机制，arr3是一个包含10个元素的向量[0,1,2,3,4,5,6,7,8,9]，它和标量1实施相加的时候，是利用了‘广播’机制，将标量扩展为[1,1,1,1,1,1,1,1,1,1]，然后进行相加

同时，arange是可以将步长设置为浮点数

In [9]:
np.arange(0,10,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

上面的的代码就代表，从0开始，到10结束，每间隔0.5生成一个数字

同时，希望在指定区间内生成指定个数的数组，且要求数组内元素之间的间隔相等，是不需要自己计算步长，可以直接使用```np.linspace(1，10，20)```，代表从1开始，到10结束，生成20个元素，中间间隔相等

In [10]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 6.3.3 Numpy数组的其他常用函数

除了上面介绍的```np.arange()```、```np.linspace()```之外，还有```np.zeros()```、```np.ones()```函数，生成指定维度和填充固定数值的数组。

```np.zeros()```，生成的数组全都用零来填充

```np.ones()```，生成的数组全都用一来填充

通常是用来初始化

In [ ]:
zeros = np.zeros((3,4)) # 生成尺寸为 3 * 4的二维数组
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

特别需要注意 上面的代码中，(3,4)是可以视为匿名元组，也是等价为 ```np.zeros(shape=(3,4))```

但确实两组括号不利于代码阅读，一般会推荐写为 ```np.zeros(shape = [3,4]) ```

In [3]:
zeros = np.zeros(shape=[3,4])
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

```zeros_like() 和 ones_like()``` 也是比较常见的方法，“借壳上市”，可以根据已有的np数组的形状进行生成，并将数值初始化为0或者1

In [4]:
zeros1 = np.zeros_like(zeros)
zeros1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
ones1 = np.ones_like(zeros1)
ones1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

和```zeros_like()```,```ones_like()```功能类似的方法还有以下两个

```empty_like()```:产生和给定数组尺寸和类型相同的数组，但该数组中的元素没有被初始化

```full_like()```:产生和给定数组尺寸和类型相同的数组，该数组中的元素都被初始化为某个给定的值

## 6.4 N维数组的属性

在物理内存中是不存在N维数组的，限于存储介质的物理特性，它永远只有一维结构。我们常见的便于理解的N维数组仅仅是“逻辑视图”​，它们不过是包装出来的。NumPy数组的物理视图和逻辑视图如图6-1所示。​“编译器”或第三方工具在幕后做了很多额外的工作，这才让我们享受到“如沐春风”般的便利。

一个N维数组就是一个通用的同类数据容器，也就是说它包含的每个元素数据类型均相同。每个数组的维度（dimension）都由一个ndim属性来描述。

In [3]:
my_array = np.arange(1,10)
my_array
my_array.ndim

1

对于N维数组而言，它还有一个重要的属性—shape（数组的形状）​。形状主要用来表征数组每个维度的数量。一维数组的形状就是它的长度，有时候，一维数组也被称为1D张量（1D Tensor）​

In [ ]:
my_array.shape

(9,)

NumPy数组形状并不是一成不变的，可以通过```reshape()```方法将原有数组变形

In [6]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
b = b.reshape(3,5)

In [10]:
b.ndim

2

一定要脑子想清楚，这个ndim是代表这是一个二维的数组，有行有列的意思。脑子要清楚

In [11]:
b.size

15

这里需要注意的是，NumPy表示三维数组维度信息的方式和我们通常的认知稍有不同。比如，我们想创建两个3行5列的数组，它的形状参数为(2, 3, 5)，而不是(3, 5,2)通常三维数组也被称为3D张量，以此类推。

In [12]:
a = np.arange(30).reshape(2,3,5)

In [13]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## 6.5 NumPy数组中的运算

数据本在，只有操作才有意义。在本节中，我们将讨论NumPy中的各种基本运算，包括向量运算、算术运算、逐元素运算等。

### 6.5.1 向量运算

In [14]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

In [15]:
list3 = [i1 + i2 for i1,i2 in zip(list1,list2)]
list3

[7, 9, 11, 13, 15]

以上是通过列表推导式的方法，来对两个向量进行逐元素求和，列表推导式的可读性并不高，而且对于编程技巧要求会更高，相应对于代码的可维护性就会更差一些。那么通过NumPy进行列表元素求和就更加直接

In [16]:
list_sum = np.array(list1)+np.array(list2)

In [17]:
list_sum

array([ 7,  9, 11, 13, 15])

### 6.5.2 算数运算

作为“久经考验”的数值计算包，NumPy有十分成熟的算术运算函数。我们无须给出复杂的计算公式，直接调用NumPy的内置函数，即可达到我们的运算目的。先来看以下代码了解一下NumPy中的简单规则。

In [18]:
a = np.arange(10)
b = np.linspace(1,10,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
a+b

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [21]:
a-b

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [22]:
a/b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [23]:
a%b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

只要操作数组的形状（维度）一致，我们就可以很方便地对它们逐元素（element-wise）实施加、减、乘、除、取余、指数运算等操作。这些操作特别适合大规模的并行计算

NumPy中还有很多好用的统计函数，如sum()、min()、max()、median()、mean()、average()、std()、var()分别用于求和、求最小值、求最大值、求中位数、求平均数、求加权平均数、求标准差、求方差。NumPy中还有很多常用的数学函数，如三角函数sin()、cos()和tan()等，这也使得导入了NumPy后，Python宛若一个功能强大的科学计算器。当然，NumPy提供的函数远不止这些，若要娴熟运用它，多多查询NumPy的官方文档，方为正道

### 6.5.3 逐元素运算与张量点乘运算

In [26]:
a = np.array([[1,2],[3,4]])
b = np.ones((2,2))
a

array([[1, 2],
       [3, 4]])

上面要特别注意 np.ones() 参数是一个元组 (2,2)

In [27]:
b

array([[1., 1.],
       [1., 1.]])

In [28]:
a + b

array([[2., 3.],
       [4., 5.]])

二维数组加法，遵循前面提到的“元素对元素”的原则，即数组a中第1行第1列的数值“1”​，和数组b中第1行第1列的数值“1”​，相加得到2。数组a中第1行第2列的数值“2”​，和数组b中第1行第2列的数值“1”​，相加得到3，一一对标，以此类推

二维数组（即矩阵）的乘法也是基于“元素对元素”原则实现的，即二维数组a的第1行第1列的数值“1”​，和二维数组b的第1行第1列的数值“1”相乘得到1。二维数组a的第1行第2列的数值“2”​，和二维数组b的第1行第2列的数值“1”相乘得到2，以此类推。

In [29]:
a * b

array([[1., 2.],
       [3., 4.]])

In [30]:
np.multiply(a,b)

array([[1., 2.],
       [3., 4.]])

数学意义上的矩阵乘法并不是这样的，不同形状的矩阵是可以进行乘法运算的，只要满足第一个矩阵的列数与第二个矩阵的行数相同即可。

In [31]:
a = np.arange(9).reshape(3,3)

In [32]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
b = np.ones(shape=(3,2))

In [34]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
np.dot(a,b)

array([[ 3.,  3.],
       [12., 12.],
       [21., 21.]])

这个计算是目前今天的难点，至少对我来说

最终的结果计算方式是，

a的第一行每个元素，逐一乘以 b的第一列的每个元素，然后求和，得到 结果数组第一行第一列的结果 （0*1 + 1 * 1 + 2 * 1） = 3

a的第一行每个元素，逐一乘以 b的第二列的每个元素，然后求和，得到 结果数组第一行第二列的结果 （0*1 + 1 * 1 + 2 * 1） = 3

那么结果数组的第一行 [3,3]

接着继续

a的第二行每个元素 逐一乘以 b的第一列的每个元素，然后求和，得到 结果数组第二行第一列的结果 (3 * 1 + 4 * 1 + 5 * 1) = 12

a的第二行每个元素 逐一乘以 b的第二列的每个元素，然后求和，得到 结果数组第二行第一列的结果 (3 * 1 + 4 * 1 + 5 * 1) = 12

那么结果数组的第二行 [12,12]

接着继续

a的第三行每个元素，逐一乘以 b的第一列的每个元素，然后求和，得到 结果数组第三行第一列的结果 (6 * 1 + 7 * 1 + 8 *1) = 21

a的第三行每个元素，逐一乘以 b的第二列的每个元素，然后求和，得到 结果数组第三行第二列的结果 (6 * 1 + 7 * 1 + 8 *1) = 21

那么结果数组的第二行 [21,21]

最终结果数组

[
    [3,3],
    [12,12],
    [21,21]
]

我们还可以直接将数组a和数组b显式转化为矩阵形式，然后直接相乘即可得到与点乘相同的结果

In [37]:
a = np.asmatrix(a)

In [38]:
a

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [40]:
b = np.asmatrix(b)

In [41]:
a * b

matrix([[ 3.,  3.],
        [12., 12.],
        [21., 21.]])