# 第6章 NumPy向量计算

除了提供很多好用的官方库之外，Python社区也贡献了很多解决特定问题的第三方库。用于Python的量化解决方案NumPy，就是其中的佼佼者。在本章中，我们将主要讨论NumPy数组的构建、方法和属性、NumPy的广播和布尔索引等。

本章学习要点

[ ] 掌握NumPy数组的使用

[ ] 理解爱因斯坦求和约定

[ ] 理解NumPy约减的轴方向

[ ] 理解NumPy的布尔索引

[ ] 掌握NumPy的广播技术

[ ] 掌握NumPy中随机模块的使用方法

## 6.1 为何需要NumPy

## 6.2 如何导入NumPy

In [1]:
import numpy as np

## 6.3 生成NumPy数组

NumPy最重要的一个特点就是支持N维数组对象ndarray。NumPy的数组只能是同一种数据类型。

### 6.3.1 利用序列生成

In [3]:
data1 = [7,8,5,5,1]
arr1 = np.array(data1)
arr1
type(arr1)

numpy.ndarray

In [4]:
# 查看数组的数据等类型
arr1.dtype

dtype('int64')

In [5]:
# 指定数据类型
arr1 = arr1.astype('float64')
arr1.dtype

dtype('float64')

### 6.3.2 利用特定函数生成

比如```np.arange```可以直接生成，函数的原型如下：

```
arange(start,stop,step,dtype)

```

In [7]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr3 = arr3+1
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

重要的“广播”机制，arr3是一个包含10个元素的向量[0,1,2,3,4,5,6,7,8,9]，它和标量1实施相加的时候，是利用了‘广播’机制，将标量扩展为[1,1,1,1,1,1,1,1,1,1]，然后进行相加

同时，arange是可以将步长设置为浮点数

In [9]:
np.arange(0,10,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

上面的的代码就代表，从0开始，到10结束，每间隔0.5生成一个数字

同时，希望在指定区间内生成指定个数的数组，且要求数组内元素之间的间隔相等，是不需要自己计算步长，可以直接使用```np.linspace(1，10，20)```，代表从1开始，到10结束，生成20个元素，中间间隔相等

In [10]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 6.3.3 Numpy数组的其他常用函数

除了上面介绍的```np.arange()```、```np.linspace()```之外，还有```np.zeros()```、```np.ones()```函数，生成指定维度和填充固定数值的数组。

```np.zeros()```，生成的数组全都用零来填充

```np.ones()```，生成的数组全都用一来填充

通常是用来初始化

In [ ]:
zeros = np.zeros((3,4)) # 生成尺寸为 3 * 4的二维数组
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

特别需要注意 上面的代码中，(3,4)是可以视为匿名元组，也是等价为 ```np.zeros(shape=(3,4))```

但确实两组括号不利于代码阅读，一般会推荐写为 ```np.zeros(shape = [3,4]) ```

In [3]:
zeros = np.zeros(shape=[3,4])
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

```zeros_like() 和 ones_like()``` 也是比较常见的方法，“借壳上市”，可以根据已有的np数组的形状进行生成，并将数值初始化为0或者1

In [4]:
zeros1 = np.zeros_like(zeros)
zeros1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
ones1 = np.ones_like(zeros1)
ones1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

和```zeros_like()```,```ones_like()```功能类似的方法还有以下两个

```empty_like()```:产生和给定数组尺寸和类型相同的数组，但该数组中的元素没有被初始化

```full_like()```:产生和给定数组尺寸和类型相同的数组，该数组中的元素都被初始化为某个给定的值

## 6.4 N维数组的属性

在物理内存中是不存在N维数组的，限于存储介质的物理特性，它永远只有一维结构。我们常见的便于理解的N维数组仅仅是“逻辑视图”​，它们不过是包装出来的。NumPy数组的物理视图和逻辑视图如图6-1所示。​“编译器”或第三方工具在幕后做了很多额外的工作，这才让我们享受到“如沐春风”般的便利。

一个N维数组就是一个通用的同类数据容器，也就是说它包含的每个元素数据类型均相同。每个数组的维度（dimension）都由一个ndim属性来描述。

In [3]:
my_array = np.arange(1,10)
my_array
my_array.ndim

1

对于N维数组而言，它还有一个重要的属性—shape（数组的形状）​。形状主要用来表征数组每个维度的数量。一维数组的形状就是它的长度，有时候，一维数组也被称为1D张量（1D Tensor）​

In [ ]:
my_array.shape

(9,)

NumPy数组形状并不是一成不变的，可以通过```reshape()```方法将原有数组变形

In [6]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
b = b.reshape(3,5)

In [10]:
b.ndim

2

一定要脑子想清楚，这个ndim是代表这是一个二维的数组，有行有列的意思。脑子要清楚

In [11]:
b.size

15

这里需要注意的是，NumPy表示三维数组维度信息的方式和我们通常的认知稍有不同。比如，我们想创建两个3行5列的数组，它的形状参数为(2, 3, 5)，而不是(3, 5,2)通常三维数组也被称为3D张量，以此类推。

In [12]:
a = np.arange(30).reshape(2,3,5)

In [13]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## 6.5 NumPy数组中的运算

数据本在，只有操作才有意义。在本节中，我们将讨论NumPy中的各种基本运算，包括向量运算、算术运算、逐元素运算等。

### 6.5.1 向量运算

In [14]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

In [15]:
list3 = [i1 + i2 for i1,i2 in zip(list1,list2)]
list3

[7, 9, 11, 13, 15]

以上是通过列表推导式的方法，来对两个向量进行逐元素求和，列表推导式的可读性并不高，而且对于编程技巧要求会更高，相应对于代码的可维护性就会更差一些。那么通过NumPy进行列表元素求和就更加直接

In [16]:
list_sum = np.array(list1)+np.array(list2)

In [17]:
list_sum

array([ 7,  9, 11, 13, 15])

### 6.5.2 算数运算

作为“久经考验”的数值计算包，NumPy有十分成熟的算术运算函数。我们无须给出复杂的计算公式，直接调用NumPy的内置函数，即可达到我们的运算目的。先来看以下代码了解一下NumPy中的简单规则。

In [18]:
a = np.arange(10)
b = np.linspace(1,10,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
a+b

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [21]:
a-b

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [22]:
a/b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [23]:
a%b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

只要操作数组的形状（维度）一致，我们就可以很方便地对它们逐元素（element-wise）实施加、减、乘、除、取余、指数运算等操作。这些操作特别适合大规模的并行计算

NumPy中还有很多好用的统计函数，如sum()、min()、max()、median()、mean()、average()、std()、var()分别用于求和、求最小值、求最大值、求中位数、求平均数、求加权平均数、求标准差、求方差。NumPy中还有很多常用的数学函数，如三角函数sin()、cos()和tan()等，这也使得导入了NumPy后，Python宛若一个功能强大的科学计算器。当然，NumPy提供的函数远不止这些，若要娴熟运用它，多多查询NumPy的官方文档，方为正道

### 6.5.3 逐元素运算与张量点乘运算

In [26]:
a = np.array([[1,2],[3,4]])
b = np.ones((2,2))
a

array([[1, 2],
       [3, 4]])

上面要特别注意 np.ones() 参数是一个元组 (2,2)

In [27]:
b

array([[1., 1.],
       [1., 1.]])

In [28]:
a + b

array([[2., 3.],
       [4., 5.]])

二维数组加法，遵循前面提到的“元素对元素”的原则，即数组a中第1行第1列的数值“1”​，和数组b中第1行第1列的数值“1”​，相加得到2。数组a中第1行第2列的数值“2”​，和数组b中第1行第2列的数值“1”​，相加得到3，一一对标，以此类推

二维数组（即矩阵）的乘法也是基于“元素对元素”原则实现的，即二维数组a的第1行第1列的数值“1”​，和二维数组b的第1行第1列的数值“1”相乘得到1。二维数组a的第1行第2列的数值“2”​，和二维数组b的第1行第2列的数值“1”相乘得到2，以此类推。

In [29]:
a * b

array([[1., 2.],
       [3., 4.]])

In [30]:
np.multiply(a,b)

array([[1., 2.],
       [3., 4.]])

数学意义上的矩阵乘法并不是这样的，不同形状的矩阵是可以进行乘法运算的，只要满足第一个矩阵的列数与第二个矩阵的行数相同即可。

In [31]:
a = np.arange(9).reshape(3,3)

In [32]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
b = np.ones(shape=(3,2))

In [34]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
np.dot(a,b)

array([[ 3.,  3.],
       [12., 12.],
       [21., 21.]])

这个计算是目前今天的难点，至少对我来说

最终的结果计算方式是，

a的第一行每个元素，逐一乘以 b的第一列的每个元素，然后求和，得到 结果数组第一行第一列的结果 （0*1 + 1 * 1 + 2 * 1） = 3

a的第一行每个元素，逐一乘以 b的第二列的每个元素，然后求和，得到 结果数组第一行第二列的结果 （0*1 + 1 * 1 + 2 * 1） = 3

那么结果数组的第一行 [3,3]

接着继续

a的第二行每个元素 逐一乘以 b的第一列的每个元素，然后求和，得到 结果数组第二行第一列的结果 (3 * 1 + 4 * 1 + 5 * 1) = 12

a的第二行每个元素 逐一乘以 b的第二列的每个元素，然后求和，得到 结果数组第二行第一列的结果 (3 * 1 + 4 * 1 + 5 * 1) = 12

那么结果数组的第二行 [12,12]

接着继续

a的第三行每个元素，逐一乘以 b的第一列的每个元素，然后求和，得到 结果数组第三行第一列的结果 (6 * 1 + 7 * 1 + 8 *1) = 21

a的第三行每个元素，逐一乘以 b的第二列的每个元素，然后求和，得到 结果数组第三行第二列的结果 (6 * 1 + 7 * 1 + 8 *1) = 21

那么结果数组的第二行 [21,21]

最终结果数组

[
    [3,3],
    [12,12],
    [21,21]
]

我们还可以直接将数组a和数组b显式转化为矩阵形式，然后直接相乘即可得到与点乘相同的结果

In [37]:
a = np.asmatrix(a)

In [38]:
a

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [40]:
b = np.asmatrix(b)

In [41]:
a * b

matrix([[ 3.,  3.],
        [12., 12.],
        [21., 21.]])

## 6.6 爱因斯坦求和约定

前面我们简单讨论了基于NumPy的矩阵操作。事实上，关于矩阵运算，NumPy还提供了一个非常好用但不为人知的方法einsum()，它根据“爱因斯坦求和约定”来执行一些求和操作。

einsum()并不是一个简单的求和运算方法，而是一个高效的符号计算规则，它可实现矩阵的各种求和操作（如点乘、转置、矩阵求迹等）​，被称为NumPy的“暗宝”​。

在深度学习框架（如TensorFlow或PyTorch）中，einsum()还可用于神经网络架构的任意计算图，并支持反向传播计算，所以值得我们掌握。

### 6.6.1 不一样的标记法

前面提到的NumPy方法名称einsum，其全称是Einstein summation convention（爱因斯坦求和约定）​，又称为爱因斯坦标记法（Einstein notation）​。在处理关于坐标的方程式时，这个方法非常有用。这是由大名鼎鼎的物理学家阿尔伯特·爱因斯坦（Albert Einstein）于1916年提出的。这种约定，简单来说，就是省去了求和式中的求和符号。我们来看下面的点乘公式。

### 6.6.2 NumPy中的enisum()方法

einsum()方法，在理论上，可以支持任意多的参数。但如图6-6所示的那样，该方法的第一个参数—格式字符串，至关重要，它直接决定整个方法实现的功能。格式字符串的规定如下

1. 不同的输入变量格式字符之间要用逗号分隔开，且输入格式字符的数量要与参与运算的变量数量相匹配。

2. 输入格式字符和输出格式字符要用箭头分隔开。

3. 输入格式字符和输出格式字符都是一系列常见字符（如ASCII码）​。

4. 格式字符串中的字符数（字符串长度）和张量的维数相对应。如字符串“ij”表示二维张量，​“ijk”表示三维张量。

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
sum1 = np.einsum('i->',arr)

In [5]:
sum1

np.int64(45)

格式字符串'i->'表示的是一个一维张量（箭头前面的字符长度为1）​，它的维度消失了（箭头后面的字符为空，其实是变成了一个标量）​，怎么才能达到这个效果呢？再结合einsum()方法的关键词“sum”可知，原来是通过“求和”达成的“约减”​。

看起来就是一次“降维打击”

In [7]:
arr2 = np.arange(20).reshape(4,5)

In [8]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
sum_col = np.einsum('ij->j',arr2) # 按列求和，也可以视为把这个数组自上而下的压扁

In [10]:
sum_col

array([30, 34, 38, 42, 46])

In [11]:
sum_row = np.einsum('ij->i',arr2)

In [12]:
sum_row

array([10, 35, 60, 85])

In [ ]:
result = np.einsum('i...->...',arr) # 降维求和

In [14]:
result

np.int64(45)

In [15]:
A = np.array([[1,1,1],
             [2,2,2],
             [5,5,5]])
B = np.array([[0,1,0],
             [1,1,0],
             [1,1,1]])


In [16]:
result = A @ B

In [17]:
result

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [18]:
result2 = np.einsum('ij,jk->ik',A,B)

In [19]:
result2

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [21]:
a = np.array([[1,2],[3,4]])

In [22]:
b = np.ones(shape=(2,2))

In [ ]:
np.einsum('ij,ij->ij',a,b) # 按元素乘

array([[1., 2.],
       [3., 4.]])

In [25]:
AA = np.array([[11,12,13,14],
                [21,22,23,24],
                [31,32,33,34],
                [41,42,43,44]])

In [ ]:
np.einsum('ii->i',AA) # 抽取对角线

array([11, 22, 33, 44])

In [27]:
np.einsum('ii->',AA) # 迹，求对角线的和

np.int64(110)

In [ ]:
np.einsum('ij->ji',AA) # 矩阵的转置

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

## 6.7 NumPy中的“轴”方向

在NumPy的多维数组中，常有“约减”​（Reduce，亦有文献译作“规约”​）的提法。它表示将众多数据按照某种规则合并成一个或几个数据。​“约减”之后，数据的个数在总量上是减少的。

在这里，​“约减”的“减”并非减法之意，而是元素的减少。比如说，数组的加法操作就是一种“约减”操作，因为它对众多元素按照加法指令实施操作，最后合并为少数的一个或几个值。示例代码如下。

In [1]:
import numpy as np

In [2]:
a = np.ones((2,3))

In [3]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
a.sum()

np.float64(6.0)

In [ ]:
a.sum(axis=0) # 垂直方向

array([2., 2., 2.])

In [ ]:
a.sum(axis=1) # 水平方向

array([3., 3.])

对于高维数组而言，​“约减”也可以有先后顺序。因此，axis的值还可以是一个向量，比如说axis=[1, 0]​，表示先进行水平方向约减，再进行垂直方向约减。反之，axis=[0, 1]表示先进行垂直方向约减，再进行水平方向约减。如果没有指定方向，那么将采用默认值None，表示所有维度都会被依次“约减”​，

更加普适的解释，应该是按括号层次来理解。括号由外到内，对应从小到大的维数。比如，对于一个三维的数组[​[​[1, 1, 1], [2, 2, 2]​], [​[3, 3, 3],[4, 4, 4]​]​]​，它有三层括号，其维度由外到内分别为[0,1,2]

这里最重要的理解就是从外到内 0 代表第0个维度，也就是最外面的括号，依次向内

In [9]:
a = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [10]:
a.ndim

3

In [11]:
a

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [12]:
a.sum(axis=0)

array([[4, 4, 4],
       [6, 6, 6]])

In [13]:
a.sum(axis=1)

array([[3, 3, 3],
       [7, 7, 7]])

In [15]:
a.sum(axis=2)

array([[ 3,  6],
       [ 9, 12]])

事实上，每个维度“约减”之后都会消失。这和前面提到的einsum()导致的“降维打击”是一回事。

“降维打击”的维度，由axis参数来指定，比如axis为0时，就是把第0维“干掉”​。具体如何干掉呢？其实就是在这个维度上执行求和等操作！完整表述就是对第0维执行求和操作，从而达到约减第0维的效果。

## 6.8 操作数组元素

我们将重点讨论如何利用NumPy来操作数组中的元素，内容包括通过索引访问数组元素、通过切片技术批量访问数组元素，以及实现二维数组的转置和展平。

### 6.8.1 通过索引访问数组元素

这里的索引，就是类似之前学习C语言的索引是一个意思，可以把数组名称当作指针，索引就是偏离这个指针的偏移量

In [16]:
one_dim = np.linspace(-0.5,0.6,12)

In [17]:
print(one_dim)

[-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5  0.6]


In [18]:
one_dim[0]

np.float64(-0.5)

In [19]:
one_dim[-1]

np.float64(0.6)

In [20]:
one_dim[0]

np.float64(-0.5)

In [21]:
print(one_dim)

[-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5  0.6]


### 6.8.2NumPy中的切片访问

与Python中列表的操作类似，除了通过索引访问数组元素，在NumPy中还可以通过切片操作来访问和修改数组数据。通过切片操作，我们可以批量获取符合要求的元素。切片操作的核心是从原始数组中，按照给定规则提取出一个新的数组，对原始数组没有任何影响。

In [3]:
import numpy as np

In [11]:
a = np.arange(10)

In [12]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
s = slice(0,9,2)

In [14]:
s

slice(0, 9, 2)

In [15]:
b = a[s]

In [16]:
b

array([0, 2, 4, 6, 8])

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

不过实际，切片更普遍的使用方法是:数组名[start:end:step]的用法

In [18]:
a[0:9:2]

array([0, 2, 4, 6, 8])

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

切片操作的参数“start: end: step”可以有很多简写方式，其中start、end和step这三个参数可根据需要选择性地省略。由于这些简写方式在NumPy操作中比较常见，下面我们便对这一点进行系统性的总结：如果start从0开始，start可省略；如果直到最末元素，end可省略；如果步长为1（取默认值）​，step可省略。

其实这也是我不太喜欢用Python的一个原因，太灵活了，不过也是我实际用的太少吧，多写才是第一位

In [20]:
a[::-1] # 倒置整个数组，这个用法真是太逆天了

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 6.8.3 二维数组的转置与展平

我们可以通过transpose()方法将二维数组转置

In [23]:
two_dim = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
two_dim.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
two_dim # 前面的transpose并不影响原数组

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

我们需要将多维数组降维成一维数组，这时我们可以利用ravel()方法来完成这个功能

In [27]:
two_dim.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
two_dim # 同样不影响原数组

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
two_dim.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

```flatten()```和```ravel()```都可以完成数组的降维，但```flatten()```会重新分配内存，完成一次从原始数据到新内存空间的深拷贝，但原始数组并没有发生变化。但ravel()其实是返回的原数组的视图，是依赖原数组的数据

In [32]:
a1 = np.array([[1,2],[3,4]])

In [34]:
ar1 = a1.ravel()

In [35]:
ar1

array([1, 2, 3, 4])

In [36]:
a1[0][0] = 100

In [37]:
a1

array([[100,   2],
       [  3,   4]])

In [ ]:
ar1 # 这个时候，尽管维度还是从原数组的二维降到一维，但其实值还是依赖原数组的，但用flatten的话，两者是毫无关系了

array([100,   2,   3,   4])

还可以用变形的方式完成数组的"降维"【这个方式也好难懂,其实并不是真正的降维】

In [39]:
two_dim.shape = [1,-1]

In [40]:
two_dim

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
two_dim.shape

(1, 9)

对于N维数组，当N-1维尺寸确定后，用“-1”标记剩余维度，表示让系统推算剩余维度尺寸，这种做法在高维数组操作中（如深度学习框架TensorFlow）很常用，因此该技巧值得掌握。

## 6.9 NumPy中的广播

广播机制是NumPy的一个“巨大”的语法糖。书中提到的是可以用“智能填充”来解释。当对两个数组进行运算的时候，如果他们的形状不同，会自动把低纬的数组扩充进行匹配，让计算可以进行。

In [44]:
a = np.arange(10)

In [45]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a + 10 # 广播填充

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
a.shape

(10,)

这种“智能”填充还会发生在两个数组之间

In [49]:
a = np.ones((3,3))

In [50]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
b = np.arange(3)

In [52]:
b

array([0, 1, 2])

In [53]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [54]:
c = np.arange(10)

In [ ]:
a + c # 这个会执行失败，广播机制必须要有一维相等

ValueError: operands could not be broadcast together with shapes (3,3) (10,) 

In [56]:
d = np.ones(19)

In [ ]:
a + d

ValueError: operands could not be broadcast together with shapes (3,3) (19,) 

基于上面成功和失败的情况，可以总结如下

扩展维度：如果两个张量的尺寸不同，广播机制会为尺寸较小的张量添加一个轴（广播轴），使其维度信息与较大张量相同

复制数据：尺寸较小的张量沿着新添加的轴不断重复之前的元素，直至尺寸与较大的张量相同

低纬有1:如果两个张量的尺寸在任何维度上都不匹配，则需将某维度中尺寸为1的张量拉伸，以匹配另一个较大张量的尺寸。【需要结合下面一句来理解】

如果两个张量在任何维度上尺寸不一致，则两者均没有任何一个维度为1，则会出现广播错误。

总结如上：要么有一个维度的尺寸相同，要么为1

## 6.10 NumPy数组的高级索引

### 6.10.1 “花式”索引

“花式”索引是指，将多个需要访问元素的索引汇集起来，构成一个整型数组，然后把这个内含索引的数组，整体作为目标数组的索引，这样就能一次性地读取多个“杂乱无序”甚至重复的数组元素。由于这种读取数组元素的方式有些花哨，故称“花式”索引，又因为索引都是整数，亦有文献称之为整数索引。

In [58]:
normal_array = np.array([34,45,56,69,9,11,22,71,82,10,123])

In [59]:
normal_array

array([ 34,  45,  56,  69,   9,  11,  22,  71,  82,  10, 123])

In [ ]:
fancy_index_array = normal_array[[0,8,7,7]] # 这个用法可是真秀啊

In [62]:
fancy_index_array


array([34, 82, 71, 71])

前面提到的花式索引，其处理的目标对象是一维数组，如果需要处理的对象变成二维数组该怎么办呢？如果还是简单套用一维数组的花式索引读取方式，程序并不会报错，但表示的含义就迥然不同了。这些二维数组中的花式索引特指“行”索引

In [63]:
two_dim_array = np.arange(20).reshape(4,5)

In [64]:
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
two_dim_array[[0,2,1,0]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [ ]:
two_dim_array[[0,0,0,0,0]] # 这么看更合适，就都是取第0行的元素

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [67]:
row_index = [0,2,1,0]

In [ ]:
two_dim_array[row_index] # 这样代码就更有可读性

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

我们也能“花式”访问二维数组的不同列

In [69]:
col_index = [0,2,4,4]

In [70]:
two_dim_array[:,col_index]

array([[ 0,  2,  4,  4],
       [ 5,  7,  9,  9],
       [10, 12, 14, 14],
       [15, 17, 19, 19]])

### 6.10.2 布尔索引

事实上，相比于“花式”索引，布尔索引的功能也不逊色，用处也非常广泛。前面的例子已经给我们提供了部分感性的认识，通过布尔索引，我们可以有选择性地提取数组中感兴趣的行或列（对应位置为True的保留，反之则过滤）​。比如，我们想要输出数组中大于某个值的所有元素，可以如下方式来实现。

In [71]:
a = np.arange(10).reshape(2,5)

In [72]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a>5 # 真是花式啊

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

## 6.11 数组的堆叠操作

我们需要将不同的NumPy数组，通过堆叠（stack）操作，拼接为一个新的较大的数组。堆叠方式大致分为水平方向堆叠（horizontal stack）​、垂直方向堆叠（vertical stack）​、深度方向堆叠（depth-wise stack）

### 6.11.1 水平方向堆叠 hstack()

In [76]:
arr1 = np.zeros(shape=(2,2),dtype=np.int8)

In [77]:
arr1

array([[0, 0],
       [0, 0]], dtype=int8)

In [78]:
arr2 = np.ones(shape=(2,3),dtype=np.int8)

In [79]:
arr2

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [81]:
np.hstack((arr1,arr2)) # 一定要注意，这里的参数是元组

array([[0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1]], dtype=int8)

In [ ]:
np.concatenate((arr1,arr2),axis=1) #利用concatenate()函数，并设置水平轴方向（axis=1）的连接，也可以达到相同的堆叠效果

array([[0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1]], dtype=int8)

### 6.11.2 垂直方向堆叠vstack()

In [85]:
arr2 = np.ones(shape=(2,3),dtype=np.int8)

In [87]:
arr3 = np.zeros(shape=(3,3),dtype=np.int8)

In [89]:
np.vstack((arr2,arr3))

array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
np.concatenate((arr2,arr3),axis=0) # 使用concatenate方法同样的效果

array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

### 6.11.3 深度方向堆叠hstack()

In [91]:
red = np.arange(0,9)

In [92]:
red

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
green = np.arange(9,18)

In [ ]:
green

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [95]:
blue = np.arange(18,27)

In [96]:
np.dstack((red,green,blue))

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20],
        [ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23],
        [ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

这里red、green、blue都是一维数组，如果改成二维数组的话，在深度方向的堆叠，这里书中是比喻为三张单色的图片叠加在一起形成一张彩色图片【我不是特别理解】，先照着把代码写了下

In [97]:
red2 = np.arange(0,9).reshape(3,3)

In [98]:
red2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
green2 = np.arange(9,18).reshape(3,3)

In [100]:
green2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [101]:
blue2 = np.arange(18,27).reshape(3,3)

In [102]:
blue2

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [103]:
np.dstack((red2,green2,blue2))

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

### 6.11.4 列堆叠与行堆叠

In [104]:
one = np.arange(3)

In [105]:
one

array([0, 1, 2])

In [106]:
two = 2 * one

In [107]:
two

array([0, 2, 4])

In [ ]:
np.column_stack((one,two)) # 和水平方向的hstack()是“殊途同归”

array([[0, 0],
       [1, 2],
       [2, 4]])

In [110]:
ones = np.arange(9).reshape(3,3)

In [111]:
ones

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
twices = 2 * ones

In [113]:
twices

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [115]:
np.column_stack((ones,twices))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [116]:
np.hstack((ones,twices)) == np.column_stack((ones,twices))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
np.row_stack((ones,twices)) # DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.

/var/folders/30/j26l_l5j1g3f7ldvbdc9q4240000gn/T/ipykernel_61784/2014946323.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((ones,twices))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### 6.11.5 数组的分割操作

In [118]:
array1 = np.arange(16).reshape(4,4)

In [119]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
list_arr = np.hsplit(array1,2) # 从中间劈了一刀

In [122]:
type(list_arr)

list

In [123]:
len(list_arr)

2

In [124]:
list_arr[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [125]:
type(list_arr[0])

numpy.ndarray

In [135]:
array2 = np.arange(16).reshape(2,8)

In [136]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [137]:
split_array = np.hsplit(array2,[2,4,6])

In [138]:
split_array

[array([[0, 1],
        [8, 9]]),
 array([[ 2,  3],
        [10, 11]]),
 array([[ 4,  5],
        [12, 13]]),
 array([[ 6,  7],
        [14, 15]])]

In [141]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:
np.vsplit(array1,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## 6.12 NumPy中的随机数模块

In [143]:
rdm = np.random.RandomState(1)

In [ ]:
rand = np.random.rand(2,3) # 生成2*3的二维随机数组，随机数服从均匀分布

In [147]:
print(rand)

[[0.74057315 0.18446406 0.54473707]
 [0.18696702 0.52587432 0.50463864]]


In [ ]:
rand = np.random.randn(2,3) # 生成2*3的二维随机数组，随机数服从正态分布
print(rand)

[[-1.94411263 -2.11661168  0.81703629]
 [-2.46562258  2.34825826  1.12229424]]


In [151]:
randint = np.random.randint(1,10,(2,3)) # 生成2*3的1-10内的随机数
print(randint)

[[3 2 4]
 [3 5 1]]


## 6.13 本章小结

在本章中，我们学习了Python中非常有用的第三方库—NumPy。要想利用Python进行数据分析，NumPy是必备的基本功。

具体说来，首先我们学习了NumPy的基础知识，NumPy支持数组与矩阵运算，此外也针对数组运算提供了大量的数学函数库，因此它支持线性代数、随机数生成及傅里叶变换功能。

在NumPy中，N维数组对象ndarray功能强大，值得我们重点掌握，本章我们主要学习了如何生成ndarray、如何基于ndarray进行各种运算、数组的切片访问、高级索引、广播机制等。